site_name: Curling
site_description: Documentation
site_author: George Ogden
site_url: https://curling.readthedocs.io    
strict: false # TODO: Don't allow warning during the build process.

# Git repo
repo_name: George-Ogden/curling
repo_url: https://github.com/George-Ogden/curling

# Navigation Map
nav:
  - Home: index.md
  - API Reference:
    - Curling: api/curling.md
    - Enums: api/enums.md
    - StoneThrow: api/stone_throw.md   

# Configuration
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  language: en
  palette:
    - scheme: slate
      primary: black
      accent: lime
  features:
    - navigation.tracking # the URL is automatically updated with the active anchor
    - navigation.sections # top-level sections are rendered as groups in the sidebar
    - navigation.tabs # horizontal tabs at the top of the page
    - navigation.tabs.sticky # navigation tabs will lock below the header and always remain visible when scrolling
    - navigation.indexes # documents can be directly attached to sections
    - search.highlight # highlight search result
    - search.share # share button
    - search.suggest # smart suggestion
    - toc.integrate
    - toc.follow
    - content.code.annotate
    - navigation.tabs
    - navigation.top

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.pathconverter:
      base_path: ./
      relative_path: docs
  - toc:
      permalink: "#"
      toc_depth: 3
  - pymdownx.highlight:
      linenums: true
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid

plugins:
  - search
  - autorefs
  - git-revision-date
  - include-markdown
  - mermaid2 # Class diagrams, flowcharts and more
  - mkdocstrings:
    #   custom_templates: templates/
      default_handler: python
      handlers:
        python:
          paths: [./curling]
          options:
            docstring_style: google
            merge_init_into_class: yes
            show_submodules: no
          selection:
            inherited_members: false
          rendering:
            show_source: false
            members_order: source
            show_if_no_docstring: true
            show_signature: true
            show_signature_annotations: true
            show_root_full_path: false
            show_root_heading: true
            merge_init_into_class: true
            docstring_section_style: spacy